# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: datum.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='datum.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x0b\x64\x61tum.proto\"b\n\x0bSimpleDatum\x12\x0c\n\x04\x64\x61ta\x18\x01 \x02(\x0c\x12\r\n\x05label\x18\x02 \x01(\x0c\x12\x10\n\x08\x64\x61ta_dim\x18\x03 \x01(\x05\x12\x11\n\tlabel_dim\x18\x04 \x01(\x05\x12\x11\n\twave_name\x18\x05 \x01(\x0c')
)




_SIMPLEDATUM = _descriptor.Descriptor(
  name='SimpleDatum',
  full_name='SimpleDatum',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='SimpleDatum.data', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='label', full_name='SimpleDatum.label', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data_dim', full_name='SimpleDatum.data_dim', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='label_dim', full_name='SimpleDatum.label_dim', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='wave_name', full_name='SimpleDatum.wave_name', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=113,
)

DESCRIPTOR.message_types_by_name['SimpleDatum'] = _SIMPLEDATUM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SimpleDatum = _reflection.GeneratedProtocolMessageType('SimpleDatum', (_message.Message,), dict(
  DESCRIPTOR = _SIMPLEDATUM,
  __module__ = 'datum_pb2'
  # @@protoc_insertion_point(class_scope:SimpleDatum)
  ))
_sym_db.RegisterMessage(SimpleDatum)


# @@protoc_insertion_point(module_scope)
